site_name: PI1 - Grupo 02
site_description: Documentação do Projeto Integrador 1 - Micromouse
site_url: https://fcte-pi1.github.io/2026_2_PI1_Grupo02_Bruno/

theme:
  name: material
  language: pt-BR
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy

nav:
  - Início: README.md

  - Especificações:
      - TAP: "1 - TAP.md"
      - Requisitos: "2 - Requisitos.md"
      - EAP: "3 - EAP.md"

  - Solução:
      - Hardware: "4.3 - Projeto conceitual de hardware.md"
      - Software: "4.4 - Projeto conceitual de software.md"
      - Estrutura: "4.1 - Projeto conceitual de estruturas.md"
      - Energia: "4.2 - Projeto conceitual de energia.md"

  - Planejamento:
      - Cronograma: "5 - Cronograma.md"
      - Orçamento: "6 - Orçamento.md"

  - Validação:
      - Testes de estrutura: "7.1 - Testes de estrutura.md"
      - Testes de energia: "7.2 - Testes de energia.md"
      - Testes de hardware: "7.3 - Testes de hardware.md"
      - Testes de software: "7.4 - Testes de software.md"
      - Testes de integração: "7.5 - Testes de integração.md"
      - Avaliação de desempenho: "8 - Avaliação de desempenho.md"

  - Entregas:
      - Relatório final: "9 - Relatório de encerramento do projeto.md"