spring.application.name=backend
server.port=${SERVER_PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/ratocego}
spring.datasource.username=${DATABASE_USERNAME:ratocego}
spring.datasource.password=${DATABASE_PASSWORD:ratocego}
spring.jpa.open-in-view=false

app.mqtt.server-uri=${MQTT_SERVER_URI:tcp://localhost:1883}
app.mqtt.client-id=${MQTT_CLIENT_ID:ratocego-backend}
app.mqtt.topic-prefix=${MQTT_TOPIC_PREFIX:ratocego}
